apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: model-mesh
  app.kubernetes.io/part-of: model-mesh
resources:
- ../default
- ../dependencies/quickstart.yaml
- ../runtimes
- ../prometheus
