kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-pachyderm
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/attach
  - pods/exec
  - secrets
  - services
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aiml.pachyderm.com
  resources:
  - pachyderms
  verbs:
  - get
  - create
  - delete
  - update
  - list
  - watch
